//
//  UPCMaxNotifications.m
//  iSomUPC
//
//  Created by Jose Gonzalez Gomez on 20/12/11.
//  Copyright (c) 2011 UPCnet. All rights reserved.
//

NSString * const TIMELINE_REFRESHED_NOTIFICATION = @"TIMELINE_REFRESHED_NOTIFICATION";
NSString * const TIMELINE_REFRESH_ERROR_NOTIFICATION = @"TIMELINE_REFRESH_ERROR_NOTIFICATION";
NSString * const ACTIVITIES_REFRESHED_NOTIFICATION = @"ACTIVITIES_REFRESHED_NOTIFICATION";
NSString * const ACTIVITIES_REFRESH_ERROR_NOTIFICATION = @"ACTIVITIES_REFRESH_ERROR_NOTIFICATION";
